CREATE TABLE DEPARTMENT
(
  DEPTID number(10) NOT NULL,
  DEPTNAME varchar2(50) NOT NULL,  
  CONSTRAINT pk_dept PRIMARY KEY (DEPTID)
);

CREATE TABLE JOB
(
  JOBID number(10) NOT NULL,
  JOBNAME varchar2(50) NOT NULL,
  DEPTID number(10) NOT NULL,
  SALARY number(10) NOT NULL,
  
  CONSTRAINT pk_job PRIMARY KEY (JOBID),
  CONSTRAINT fk_dept FOREIGN KEY (DEPTID) REFERENCES DEPARTMENT (DEPTID)
);

CREATE TABLE EMPLOYEE
(
  EMPID number(10) NOT NULL,
  ENAME varchar2(50) NOT NULL,
  HIREDATE DATE NOT NULL,
  JOBID number(10) NOT NULL DEFAULT 1,
  DEPTID NUMBER(10) NOT NULL,

  CONSTRAINT pk_emp PRIMARY KEY (EMPID),
  CONSTRAINT emp_fk_dept FOREIGN KEY (DEPTID) REFERENCES DEPARTMENT(DEPTID),
  CONSTRAINT emp_fk_job FOREIGN KEY (JOBID) REFERENCES JOB(JOBID)
);




